
\version "2.24.0" % LilyPond version
\header {
  title = "Fireworks for Tenor Trombone"
  composer = "Generated by ChatGPT"
}

\score {
  \new Staff {
    \clef bass
    \tempo 4 = 120
    \time 4/4

    \relative c {
      % 16 measures of energetic, "fireworks-like" music
      c4 e g b | d' g c a | 
      g e c d | b, g f e | 
      c4 e g b | d' g c a | 
      g e c d | b, g f e | 
      c4 e g b | d' g c a | 
      g e c d | b, g f e | 
      c4 e g b | d' g c a | 
      g e c d | b, g f e |
    }
  }

  \layout { }
  \midi { \tempo 4 = 120 }
}
